name: ✨ Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement", "needs-triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for suggesting a feature! Please fill out the information below.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? Is your feature request related to a problem?
      placeholder: I'm frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like...
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature affect?
      options:
        - POS (Point of Sale)
        - KDS (Kitchen Display)
        - Reports & Analytics
        - Inventory Management
        - Product Management
        - Customer Management
        - Employee Management
        - Online Store
        - Self-Order
        - Table Management
        - Authentication & Security
        - Settings & Configuration
        - Mobile App
        - Desktop App
        - API
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Critical (Blocking current work)
        - High (Very important)
        - Medium (Nice to have)
        - Low (Future consideration)
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternative solutions or features have you considered?
      placeholder: I've considered...
    validations:
      required: false

  - type: dropdown
    id: user-type
    attributes:
      label: User Type
      description: Which type of user would benefit from this feature?
      multiple: true
      options:
        - Owner
        - Manager
        - Cashier
        - Kitchen Staff
        - Inventory Staff
        - Customer
        - All Users
    validations:
      required: true

  - type: dropdown
    id: business-size
    attributes:
      label: Business Size
      description: What size of business would benefit most?
      multiple: true
      options:
        - Small (1-5 employees)
        - Medium (6-20 employees)
        - Large (20+ employees)
        - All Sizes
    validations:
      required: false

  - type: textarea
    id: use-cases
    attributes:
      label: Use Cases
      description: Describe specific use cases or scenarios where this feature would be helpful.
      placeholder: |
        1. When a customer wants to...
        2. When staff needs to...
    validations:
      required: false

  - type: textarea
    id: mockups
    attributes:
      label: Mockups or Examples
      description: If applicable, add mockups, screenshots, or links to similar implementations.
      placeholder: Drag and drop images here or paste URLs
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples about the feature request.
      placeholder: Any additional information...
    validations:
      required: false

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues/features to ensure this is not a duplicate
          required: true
        - label: This feature aligns with TiloPOS goals (helping UMKM Indonesia)
          required: true
        - label: I am willing to contribute to implementing this feature
          required: false
