export const REPOSITORY_TOKENS = {
  PRODUCT: 'IProductRepository',
  TRANSACTION: 'ITransactionRepository',
  INVENTORY: 'IInventoryRepository',
  ORDER: 'IOrderRepository',
  CUSTOMER: 'ICustomerRepository',
  EMPLOYEE: 'IEmployeeRepository',
  SHIFT: 'IShiftRepository',
  AUDIT: 'IAuditRepository',
  PROMOTION: 'IPromotionRepository',
  SUPPLIER: 'ISupplierRepository',
  SETTINGS: 'ISettingsRepository',
  DEVICE: 'IDeviceRepository',
  ONLINE_STORE: 'IOnlineStoreRepository',
  NOTIFICATION: 'INotificationRepository',
  SETTLEMENT: 'ISettlementRepository',
  INGREDIENT: 'IIngredientRepository',
  LOYALTY: 'ILoyaltyRepository',
  TABLE: 'ITableRepository',
  CREDIT_SALE: 'ICreditSaleRepository',
} as const;
